/* automatically generated by xdrgen from xdr/asctec_Status.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/asctec_Status.xdr last modified: Mon Jul  4 18:11:16 2011
 */

#ifndef INCasctec_Status_h
#define INCasctec_Status_h


struct asctec_Status {
  unsigned int cpu_load;
  float voltage;
#define asctec_Status_IPC_FORMAT "{uint,float}"
  static const char *getIPCFormat(void) {
    return asctec_Status_IPC_FORMAT;
  }


  asctec_Status()
  {   
  }
  asctec_Status(const asctec_Status& msg)
  {    
    cpu_load = msg.cpu_load;
    voltage = msg.voltage;
  }
  ~asctec_Status()
  {
  }
  asctec_Status& operator= (const asctec_Status& msg)
  {
    cpu_load = msg.cpu_load;
    voltage = msg.voltage;

    return *this;
  }

};


namespace ipc_bridge
{
    namespace asctec
    {
        typedef asctec_Status Status;
    }
}


#endif /* INCasctec_Status_h */
